services:
  api:
    build: ./api
    container_name: api
    ports:
      - '443:443'
    volumes:
      - ./api:/api
      - ./api:/node_modules
    depends_on:
      - db
  app:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
      - ./client:/node_modules
    stdin_open: true
    tty: true
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

